# Generated by Django 5.0.1 on 2024-02-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('attendance_average', models.FloatField()),
                ('assignment_completion', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('cohort', models.CharField(choices=[('Cohort 1', 'Cohort 1'), ('Cohort 2', 'Cohort 2')])),
            ],
        ),
    ]
