FROM python:3.10-slim-bullseye

WORKDIR /api

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY ./ ./

EXPOSE 80

CMD python manage.py migrate && python manage.py loaddata students && gunicorn -b 0.0.0.0:80 nebula.wsgi:application